modLoader="javafml"
loaderVersion="[39,)"
license="The Apache License, Version 2.0"
issueTrackerURL=""

[[mods]]
modId="intturtle"
version="${file.jarVersion}"
displayName="IntTurtle"
displayURL="https://www.curseforge.com/minecraft/mc-mods/intturtle"
updateJSONURL="https://assets.melanx.de/updates/intturtle.json"
authors="noeppi_noeppi"
description="""
IntCode powered Turtles
"""

[[dependencies.intturtle]]
    modId="forge"
    mandatory=true
    versionRange="[39.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.intturtle]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.intturtle]]
    modId="libx"
    mandatory=true
    versionRange="[1.18.1-3.1.0,)"
    ordering="NONE"
    side="BOTH"

